### ISSUE TITLE
com.google.cloud.datastore.DatastoreException Unauthenticated.

### ISSUE THREAD

**Issue by aniruddhadas9** [o/spring-boot-google-cloud-datastore-sample#2]
While I run the project in local machine I am getting the below error. I have also created a [stackoverflow question](https://stackoverflow.com/questions/47583059/google-app-engine-spring-boot-local-testing-with-data-store-gives-unauthentica) 
```
{
   "timestamp": 1512077140003,
   "status": 500,
   "error": "Internal Server Error",
   "exception": "com.google.cloud.datastore.DatastoreException",
   "message": "Unauthenticated.",
   "path": "/users"
}
```

The error description [here](https://cloud.google.com/datastore/docs/concepts/errors) says the request header does not have valid authentication header, But where to place the auth header does not mentioned.

anybody faced same kind of situation?

**Comment by o** [comment]
Hi Aniruddha

You should install gcloud tools and run the following command
https://cloud.google.com/sdk/gcloud/reference/init

**Comment by aniruddhadas9** [comment]
In particular below command authenticated me to the datastore

`gcloud auth application-default login`

Thanks for this beautiful start application :)

**Comment by o** [comment]
Enjoy!
